<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function bootstrap_sass_theme_suggestions_fontawesomeicon_alter(array &$suggestions, array $variables) {
    $suggestions[] = 'font_awesome';
}

function bootstrap_sass_preprocess_field(&$variables) {
  if ($variables['submitted']) {
    $variables['submitted'] = t('!datetime !username', array('!username' => $variables['name'], '!datetime' => $variables['date']));
  }
}
